version: '3.4'

services:
  fooddelivery:
    image: ${DOCKER_REGISTRY-}fooddelivery
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8090:80"

  redis:
    image: redis
    container_name: redis_container
    ports: 
      - "6379:6379"

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Senha1234!
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
volumes:
  sqlvolume: